version: "3.9"
services:
  frontend:
    build: 
        context: .
        dockerfile: ./Dockerfile
    image: beerfest-fe
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "4001:4001"
    networks:
      - frontend

networks:
  frontend:
    name: frontend