apiVersion: v1
kind: Service
metadata:
  labels:
    app: beerfest-fe
    version: v1
  name: beerfest-fe-service
spec:
  type: ClusterIP
  ports:
  - name: beerfest-port
    port: 80
    protocol: TCP
  selector:
    app: beerfest-fe